import type { ServerBuild } from '@remix-run/cloudflare';
import { createPagesFunctionHandler } from '@remix-run/cloudflare-pages';

// @ts-ignore because the server build file is generated by `remix vite:build`
import * as serverBuild from '../build/server';

// Create the Remix handler
const remixHandler = createPagesFunctionHandler({
  build: serverBuild as unknown as ServerBuild,
});

// IP filtering logic: Fetch ALLOWED_IP from environment variables
export const onRequest: PagesFunction = async (context) => {
  try {
    // Get the IP address from the request headers (Cloudflare will add the real IP in 'cf-connecting-ip')
    const forwardedFor = context.request.headers.get('cf-connecting-ip') ||
                         context.request.headers.get('x-forwarded-for') ||
                         context.request.headers.get('x-real-ip') ||
                         '127.0.0.1';
    const requestIp = forwardedFor.split(',')[0].trim();

    // Fetch the allowed IP from environment variables
    const allowedIp = context.env.ALLOWED_IP;

    if (!allowedIp) {
      throw new Error("Environment variable ALLOWED_IP is not set.");
    }

    // Check if the request IP matches the allowed IP
    if (requestIp !== allowedIp) {
      // Return Access Denied page with styled content
      return new Response(
        `
        <!DOCTYPE html>
        <html lang="en" data-theme="light">
          <head>
            <title>Access Denied</title>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap">
            <style>
              body {
                font-family: 'Inter', sans-serif;
                background-color: #f9fafb;
                color: #000000;
                margin: 0;
                display: flex;
                align-items: center;
                justify-content: center;
                height: 100vh;
                text-align: center;
              }
              .container {
                max-width: 400px;
              }
              .title {
                font-size: 1.5rem;
                font-weight: 700;
                color: #000000;
                margin-bottom: 1rem;
              }
              .description {
                font-size: 0.875rem;
                margin: 0.5rem 0;
                color: #000000;
              }
              .support-link {
                display: inline-block;
                margin-top: 1rem;
                padding: 0.25rem 0.75rem;
                background-color: #000000;
                color: #ffffff;
                text-decoration: none;
                font-size: 0.875rem;
                border-radius: 0.25rem;
                transition: background-color 0.3s;
              }
              .support-link:hover {
                background-color: #333333;
              }
            </style>
          </head>
          <body>
            <div class="container">
              <h1 class="title">Access Denied</h1>
              <p class="description">You are not authorized to access this application.</p>
            </div>
          </body>
        </html>
        `,
        {
          status: 403,
          headers: { 'Content-Type': 'text/html' },
        }
      );
    }

    // Fetch the password from environment variables
    const AUTH_TOKEN = context.env.AUTH_TOKEN;

    if (!AUTH_TOKEN) {
      throw new Error("Environment variable AUTH_TOKEN is not set.");
    }

    // Get the 'Authorization' header from the request
    const authHeader = context.request.headers.get("Authorization");
    const expectedAuth = `Basic ${btoa(`:${AUTH_TOKEN}`)}`; // Colon to skip username.

    // Check if the 'Authorization' header matches the expected value
    if (authHeader !== expectedAuth) {
      return new Response("Unauthorized", {
        status: 401,
        headers: { "WWW-Authenticate": 'Basic realm="Protected Area"' },
      });
    }

    // If both IP check and auth check succeed, forward the request to Remix
    return remixHandler(context);
  } catch (error) {
    // Log the error and return a 500 response
    console.error("Worker error:", error);
    return new Response("Internal Server Error", { status: 500 });
  }
};
