import type { ServerBuild } from '@remix-run/cloudflare';
import { createPagesFunctionHandler } from '@remix-run/cloudflare-pages';

// @ts-ignore because the server build file is generated by `remix vite:build`
import * as serverBuild from '../build/server';

// Create the Remix handler
const remixHandler = createPagesFunctionHandler({
  build: serverBuild as unknown as ServerBuild,
});

// Helper function to render Access Denied page with Tailwind styling
function renderAccessDeniedPage() {
  return `
    <html lang="en">
      <head>
        <title>Access Denied</title>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body class="bg-gray-100 text-gray-900 font-sans">
        <div class="flex flex-col items-center justify-center min-h-screen p-6">
          <div class="text-center">
            <h1 class="text-4xl font-extrabold text-red-600 mb-6">Access Denied</h1>
            <p class="text-xl text-gray-700 mb-4">You are not authorized to access this application.</p>
            <p class="text-sm text-gray-500 mb-6">If you believe this is an error, please contact the administrator.</p>
            <a
              href="mailto:support@yourdomain.com"
              class="bg-blue-500 text-white text-base py-2 px-4 rounded hover:bg-blue-700 transition duration-300"
            >
              Contact Support
            </a>
          </div>
        </div>
      </body>
    </html>
  `;
}

// IP filtering logic: Fetch ALLOWED_IP from environment variables
export const onRequest: PagesFunction = async (context) => {
  try {
    // Get the IP address from the request headers (Cloudflare will add the real IP in 'cf-connecting-ip')
    const forwardedFor = context.request.headers.get('cf-connecting-ip') ||
                         context.request.headers.get('x-forwarded-for') ||
                         context.request.headers.get('x-real-ip') ||
                         '127.0.0.1';
    const requestIp = forwardedFor.split(',')[0].trim();

    // Fetch the allowed IP from environment variables
    const allowedIp = context.env.ALLOWED_IP;

    if (!allowedIp) {
      throw new Error("Environment variable ALLOWED_IP is not set.");
    }

    // Remove localhost access by checking for '127.0.0.1'
    if (requestIp === '127.0.0.1' || requestIp === 'localhost') {
      return new Response(renderAccessDeniedPage(), { status: 403 });
    }

    // Check if the request IP matches the allowed IP
    if (requestIp !== allowedIp) {
      // If not, return 403 Forbidden
      return new Response(renderAccessDeniedPage(), {
        status: 403,
      });
    }

    // Fetch the password from environment variables
    const AUTH_TOKEN = context.env.AUTH_TOKEN;

    if (!AUTH_TOKEN) {
      throw new Error("Environment variable AUTH_TOKEN is not set.");
    }

    // Get the 'Authorization' header from the request
    const authHeader = context.request.headers.get("Authorization");
    const expectedAuth = `Basic ${btoa(`:${AUTH_TOKEN}`)}`; // Colon to skip username.

    // Check if the 'Authorization' header matches the expected value
    if (authHeader !== expectedAuth) {
      return new Response("Unauthorized", {
        status: 401,
        headers: { "WWW-Authenticate": 'Basic realm="Protected Area"' },
      });
    }

    // If both IP check and auth check succeed, forward the request to Remix
    return remixHandler(context);
  } catch (error) {
    // Log the error and return a 500 response
    console.error("Worker error:", error);
    return new Response("Internal Server Error", { status: 500 });
  }
};
