import type { ServerBuild } from '@remix-run/cloudflare';
import { createPagesFunctionHandler } from '@remix-run/cloudflare-pages';

// @ts-ignore because the server build file is generated by `remix vite:build`
import * as serverBuild from '../build/server';

// Create the Remix handler
const remixHandler = createPagesFunctionHandler({
  build: serverBuild as unknown as ServerBuild,
});

export const onRequest: PagesFunction = async (context) => {
  try {
    // Fetch the password from environment variables
    const AUTH_TOKEN = context.env.AUTH_TOKEN;

    if (!AUTH_TOKEN) {
      throw new Error("Environment variable AUTH_TOKEN is not set.");
    }

    // Get the 'Authorization' header from the request
    const authHeader = context.request.headers.get("Authorization");
    const expectedAuth = `Basic ${btoa(`:${AUTH_TOKEN}`)}`; // Colon to skip username.

    // Check if the 'Authorization' header matches the expected value
    if (authHeader !== expectedAuth) {
      return new Response("Unauthorized", {
        status: 401,
        headers: { "WWW-Authenticate": 'Basic realm="Protected Area"' },
      });
    }

    // If authentication succeeds, forward the request to Remix
    return remixHandler(context);
  } catch (error) {
    // Log the error and return a 500 response
    console.error("Worker error:", error);
    return new Response("Internal Server Error", { status: 500 });
  }
};
